In [ ]:
import cv2
import numpy as np
import time

In [ ]:
x=600
y=600
origin=(x//2,y//2)

In [ ]:
def calculator(x, y, r1, r2, origin):
    x = x - origin[0]
    y = y - origin[1]
    dist_sq = x**2 + y**2
    cos_theta_diff = (dist_sq - r1**2 - r2**2) / (2 * r1 * r2)
    cos_theta_diff = np.clip(cos_theta_diff, -1.0, 1.0)
    theta_diff = np.arccos(cos_theta_diff)
    alpha = np.arctan2(y, x)
    cos_gamma = (r1**2 + dist_sq - r2**2) / (2 * r1 * np.sqrt(dist_sq))
    gamma = np.arccos(np.clip(cos_gamma, -1.0, 1.0))
    theta2 = alpha - gamma 
    theta = theta_diff + theta2
    phy = theta2 - theta 
    return (theta, phy)

In [ ]:
r1=100
r2=100
screen=np.ones((x,y)).astype(np.uint8)*255
for theta in range(180,360):
    cx1=r1*np.cos(np.pi/180*theta)+origin[1]
    cy1=r1*np.sin(np.pi/180*theta)+origin[0]
    for phy in range (0,180):
        cx2=cx1+ r2*np.cos(np.pi/180*(phy+theta))
        cy2=cy1+ r2*np.sin(np.pi/180*(phy+theta))
        th,ph=calculator(cx2,cy2,r1,r2,origin)
        ccx2=r1*np.cos(th)+origin[1]+ r2*np.cos((ph+th))
        ccy2=r1*np.sin(th)+origin[0]+ r2*np.sin((ph+th))
        if (ccx2==np.nan or ccy2==np.nan):
            continue
        print(f"{cx2}  {cy2}\n {ccx2}   {ccy2}\n\n\n")
        cv2.circle(screen,(int(cx2),int(cy2)),2,(0,255,0),2)
        cv2.imshow("logic",screen)
    cv2.waitKey(1)


In [ ]:
while True:
    x=int(input("enter x"))
    y=int(input("enter y"))
    theta,phy=calculator(x,y,r1,r2,origin)
    cx2=r1*np.cos(theta)+origin[1]+ r2*np.cos((phy+theta))
    cy2=r1*np.sin(theta)+origin[0]+ r2*np.sin((phy+theta))
    print(cx2,cx1)

In [ ]:
screen=np.ones((x,y)).astype(np.uint8)*255
image = cv2.imread('your_image.jpg')
gray = cv2.cvtColor(image, cv2.COLOR_BGR2GRAY)
_, thresh = cv2.threshold(gray, 127, 255, cv2.THRESH_BINARY)
contours, _ = cv2.findContours(thresh, cv2.RETR_EXTERNAL, cv2.CHAIN_APPROX_NONE)
for i, cnt in enumerate(contours):
    print(f"Contour {i} has {len(cnt)} points.")
    points = cnt.reshape(-1, 2)
    for point in points:
        x, y = point
        cv2.circle(screen,(int(x),int(y)),2,(0,255,0),2)
        cv2.imshow("logic",screen)
        cv2.waitKey(0)
        

[[255 255 255 ... 255 255 255]
 [255 255 255 ... 255 255 255]
 [255 255 255 ... 255 255 255]
 ...
 [255 255 255 ... 255 255 255]
 [255 255 255 ... 255 255 255]
 [255 255 255 ... 255 255 255]]


In [38]:
screen.shape

(600, 600)